### ISSUE TITLE
Tweak `inflateParseUser` method

### ISSUE THREAD

**Issue by theill** [ParsePlatform/parse-cloud-express#1]
I need to update the `inflateParseUser` method to patch a `req.body.user` with a className. Do you know why this is needed? Is it a change in what's being sent in a webhook payload or what could be the reason. Anyway I need to update the method to this:

    function inflateParseUser(req, res, next) {
      if (req.body.user) {
        if (req.body.user.className === undefined) {
          req.body.user.className = "_User";
        }
        req.user = Parse.Object.fromJSON(req.body.user);
      }
      req.master = req.body.master;
      next();
    }

If anyone else see this I'll make a PR.

**Comment by gfosco** [comment]
Yeah, this makes sense... If you can send a PR that would be great, thanks.

**Comment by theill** [comment]
Cool, see https://github.com/ParsePlatform/parse-cloud-express/pull/2

**Comment by gfosco** [comment]
Thanks :)
