### ISSUE TITLE
Push from webhooks fails

### ISSUE THREAD

**Issue by Vortec4800** [ParsePlatform/parse-cloud-express#10]
I'm running this on Heroku using the default Parse CLI template and setup. When trying to send a push notification from a Parse function, I get an error that says "Client-initiated push isn't enabled." I don't really want to enable client push as I understand that it is much less secure, but is it required when sending a push notification from webhooks?

My initial setup at the top of the main.js file looks like this:

```
var Parse = require('parse-cloud-express').Parse;

Parse.initialize(process.env.PARSE_APP_ID, process.env.PARSE_JS_KEY, process.env.PARSE_MASTER_KEY);
```

**Comment by gfosco** [comment]
Looks like this is currently poorly/un documented.  You can enable the master key here by passing an option:

```
Parse.Push.send({ channels: ["Giants"] }, { useMasterKey: true }).then(...
```

That option should allow the push, but I expected that this would be the default behavior in the parse/node environment.   Let mw know if you have any further issues, thanks.

**Comment by Vortec4800** [comment]
Great, thanks - I'll give that a try.
