### ISSUE TITLE
Second call of Parse.User.logIn() on node destroys previous session token

### ISSUE THREAD

**Issue by stefanraffeiner** [ParsePlatform/parse-cloud-express#12]
We use a set up similar to AnyPhone, where we generate sessionTokens on server side (nodeJS on Heroku).

Users who have two devices log in on the first one, then on the second one, after that they see the error "invalid session token" on the first device. The first session is deleted from Parse.

As far as I could reproduce the error is caused, because Parse.User.logIn() passes an installationId to Parse, even if it runs on server side. Using or not using masterKey makes no difference. It looks like there can be only one session per installation and user.
When I restart node it gets a new installationId and everything works.

To work around this issue I copied the network request from Parse.User.logIn() and created a custom login method using the Parse.Cloud.httpRequest(), wich sends the exact same request without "installationId". That way it works, I get new sessionTokens for each device and the old ones remain active.
```
var logIn = function (username, password) {
    return Parse.Cloud.httpRequest({
        method: 'POST',
        url: 'https://api.parse.com/1/login',
        headers: {
            'Content-Type': 'text/plain',
            'User-Agent': 'node-XMLHttpRequest, Parse/1.6.9 (NodeJS 4.1.2)',
            'Accept': '*/*'
        },
        body: {
            "username": username,
            "password": password,
            "_method": "GET",
            "_ApplicationId": process.env.PARSE_APP_ID,
            "_ClientVersion": "js1.6.9",
            "_MasterKey": process.env.PARSE_MASTER_KEY,
            "_RevocableSession": "1"
        },
        json: true
    });
} 
Parse.User.logIn(username, password); //-> destroys previous session token
logIn(username, password); //-> does not destroy previous session token
```

Is it the desired behavior, that server side code passes an installationId? If yes: is there any parameter I can use to avoid this session token issue? 
For now my workaround works, but I don't think this is the ideal way. How would you solve this to run AnyPhone on nodeJS?

**Comment by gfosco** [comment]
Interesting... I'd like for you to open this as an issue against the JS SDK: https://github.com/ParsePlatform/Parse-SDK-JS

That is definitely the place to discuss... Please reference this issue there, and link to that issue here once you create it.  Thanks!
