### ISSUE TITLE
Parse.Cloud.httpRequest not working with body

### ISSUE THREAD

**Issue by apat183** [ParsePlatform/parse-cloud-express#13]
Hi

I'm currently using parse cloud express on a node server and trying to make the following post request but when every I include the body in the request I'm getting the following error:

```
Parse.Cloud.httpRequest failed with error:
[Error: Argument error, options.body.]
_http_outgoing.js:439
    throw new TypeError('first argument must be a string or Buffer');
```

When I remove the body the request works fine and I get a response from the box API. I don't see anything wrong in the way I've structured my body?

```         
var url = 'https://view-api.box.com/1/settings/storage-profile';

var s3Params = {
    provider: "S3",
    s3_bucket_name: 'Somebucketname',
    s3_access_key_id: process.env.AWS_ACCESS_KEY_ID,
    s3_secret_access_key: process.env.AWS_SECRET_ACCESS_KEY
};

Parse.Cloud.httpRequest({
    method: 'POST',
    url: url,
    headers: {
        'Authorization': 'Token ' + process.env.BOX_API,
        'Content-Type': 'application/json'
    },
    body: s3Params
}).then(function (data) {

    response.success(data);

}, function (error) {

    response.error(error);
});
```

**Comment by gfosco** [comment]
This would likely work if you JSON.stringify(s3Params) when passing it to body... I don't know if we should automatically do this (does this behavior not match the hosted cloud code behavior?)

**Comment by apat183** [comment]
Yep you are right, JSON.stringify(s3Params) fixes issue. 

I haven't tried it in cloud code. I've only been hosting in Heroku.  But it also didn't work when it was hosted in Heroku.  

I was going off this documentation: https://parse.com/docs/cloudcode/guide#cloud-code-advanced-sending-a-post-request

I noticed that when I tried the example in the documentation above it was still giving the same error. I'm guessing it's not the same in cloud code.

If it helps here was the full error, 

```
Parse.Cloud.httpRequest failed with error:
[Error: Argument error, options.body.]
_http_outgoing.js:439
    throw new TypeError('first argument must be a string or Buffer');
    ^

TypeError: first argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:439:11)
    at Request.write (/Users/anandpatel/development/split-l8igil-7882/node_modules/parse-cloud-express/node_modules/request/request.js:1378:25)
    at end (/Users/anandpatel/development/split-l8igil-7882/node_modules/parse-cloud-express/node_modules/request/request.js:560:16)
    at Immediate._onImmediate (/Users/anandpatel/development/split-l8igil-7882/node_modules/parse-cloud-express/node_modules/request/request.js:588:7)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

It actually looks like it has something to do with the request node module.  I tired making a http request using the "request" module and not using Parse.Cloud.httpRequest and it was producing the same error.

Thanks
