### ISSUE TITLE
Query on Heroku returns 142: Validation failed

### ISSUE THREAD

**Issue by stefanraffeiner** [ParsePlatform/parse-cloud-express#7]
Running this code on Heroku:
```javascript
var Parse = require('parse-cloud-express').Parse;
Parse.initialize(process.env.PARSE_APP_ID, process.env.PARSE_WEBHOOK_KEY, process.env.PARSE_MASTER_KEY);
Parse.Cloud.define('test2', function (request, response) {
    var Job = Parse.Object.extend('Job'),
        query = new Parse.Query(Job),
        token = request.user.getSessionToken();
    query.find({ sessionToken: token}).then(function (results) {
        response.success(results);
    }, function (error) {
        response.error(error);
    });
});
```
returns
```javascript
{
  "code": 142,
  "error": "Validation failed"
}
```
When using MasterKey or running the same query from JS SDK or curl it works. I tried to replace the Webhook key with the JS and the Rest key, but did change anything.

The same code worked on Cloud Code (by just calling query.find() without token).

The CLP allows public users to create objects. All other permissions are granted to a specific user by a Pointer. Tried to change permissions, does not help with the error.

As workaround I could use MasterKey and query.equalTo("user". user); but I don't think that's the right solution especially as we have objects where multiple users have different (read/write) rights.

Not sure if this is a error on our side or a bug on Parse. The error occurred in a bigger project, but is reproducible with the provided code.

**Comment by gfosco** [comment]
For troubleshooting purposes, can you console.log(JSON.stringify(request.user)); and see if it has the valid fields... console.log(request.user.getSessionToken()) too.

**Comment by stefanraffeiner** [comment]
Hi Fosco
here are some logs: 
```javascript
console.log("session token:");
console.log(request.user.getSessionToken());
console.log("user:");
console.log(JSON.stringify(request.user));
console.log("query:");
console.log(JSON.stringify(query));
```
```javascript
session token:
r:mggCzhnnGXXXXXXXXXXX
user:
{"ACL":{"fXUsvYZEN4":{"read":true,"write":true}},"activated":true,"createdAt":"2015-08-21T20:35:44.919Z","email":"XXXXXX","firstName":"St", ......}
query:
{"where":{}}
```

I removed the Parse.initialize(), but it does not change anything, the copied code actually is from main.js. When using Masterkey it works.

**Comment by stefanraffeiner** [comment]
also tried to generate a new session token, same issue. The session token is generated on Heroku by calling Parse.User.logIn(username, password, {useMasterKey: true}) with masterKey. (Our authentication is similar to the AnyPhone sample app).

**Comment by stefanraffeiner** [comment]
Found it! I run the node project on my local device and logged all network requests from and to it.
The Query looks as following:
```javascript
POST api.parse.com/1/classes/Job
{
"where": {},
"_method": "GET",
"_ApplicationId": "XXXXXX",
"_JavaScriptKey": "XXXXX",
"_ClientVersion": "js1.6.9",
"_InstallationId": "XXXX",
"_SessionToken": "XXXXX"
}
```
As I initialize Parse with the webhook Key, it uses the webhook key as javascript key.
I added an additional variable "PARSE_JAVASCRIPT_KEY" to the node environment and initialize it with
```javascript
Parse.initialize(process.env.PARSE_APP_ID, process.env.PARSE_JAVASCRIPT_KEY, process.env.PARSE_MASTER_KEY);
```
The "PARSE_WEBHOOK_KEY" is still needed in parse-cloud-express/index.js
```javascript
function validateWebhookRequest(req, res, next) {
  if (req.get('X-Parse-Webhook-Key') !== webhookKey) return errorResponse(res, 'Unauthorized Request.');
  next();
} 
```
So the solution is to use both, javascript and webhook key.
@gfosco Is this the expected behavior? If so it should be mentioned in the documentation. Otherwise queries using the webhook key should be allowed.

**Comment by nnaynnay** [comment]
Had this problem too! 
Thanks for the findings @stefanraffeiner

**Comment by loftyet** [comment]
PARSE_JAVASCRIPT_KEY is the key to solve my problem.
